/* Generated by bin2c, do not edit manually */
#ifndef ____includes_logo_h_included
#define ____includes_logo_h_included

/* Contents of file .\data\logo.bin */
extern const long int __data_logo_bin_size;
extern const unsigned char __data_logo_bin[32808];

#endif    /* ____includes_logo_h_included */
